name: Amplify Console

on:
  push:
    paths:
    - 'cloudformation.yaml'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: Set Repository URL
      run: echo "::set-env name=REPOSITORY_URL::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
    # - name: Get REPOSITORY_URL
    #   run: echo "REPOSITORY_URL is " $REPOSITORY_URL
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: TodoApp
        template: cloudformation.yaml
        parameter-overrides: "OauthToken=${{ secrets.REPOSITORY_OAUTH_TOKEN }},Repository=${{ env.REPOSITORY_URL }},Domain=thesmartsuperlist.com"
        no-fail-on-empty-changeset: "1" # 1=true
        timeout-in-minutes: 10
